### ISSUE TITLE
inject our css into canvas WYSIWYG so designers can see web features without saving changes

### ISSUE THREAD

**Issue by nikhuff** [byuitechops/byui-design-lti#3]

**Comment by nikhuff** [comment]
I don't think this is possible. See answer at link: 
https://community.canvaslms.com/thread/17332-adding-css-to-content-editor

**Comment by danverde** [comment]
Please check [byui canvas theme](https://github.com/byuitechops/byui-canvas-theme/tree/tinyMCE) for solution
